stages:
  - lint
  - build

variables:
  IMAGE_NAME: $DOCKER_REPOSITORY
  TAG: latest
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""


before_script:
  - apk add --no-cache docker

lint:
  stage: lint
  image: docker:24.0.5    # используемый образ
  services:               # позволяет запустить другой контейнер
    - docker:24.0.5-dind 
  script:                 # код команды для выполнения
    - docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile

build:
  stage: build
  image: docker:20.10.7 # используем Docker image
  services:
    - docker:20.10.7-dind # Docker in Docker
  script:
    - docker info # проверка доступности Docker
    - docker build -t $IMAGE_NAME:$TAG .
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $IMAGE_NAME:$TAG
    

